sudo: required

services:
  - docker

language: minimal

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

deploy:
  # deploy master to production
  - provider: script
    script: sh ./travis/deploy_showoff.sh
    on:
      branch: master
